name: PR Workflow

on:
  # implemented this otherwise the workflow would run twice on every push (once for the PR and once for the push)
  pull_request:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
    branches:
      - main
    types: [opened, reopened, labeled, unlabeled, synchronize, closed]

concurrency:
  # Added to stop multiple runs of the workflow for the same branch or PR. This is because we only care about the latest run for a branch/PR and it saves resources by cancelling any in progress runs when a new commit is pushed. The concurrency group is defined as the workflow name and the branch or PR ref to ensure that runs are only cancelled for the same branch or PR.
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write # Needed for checkout
  actions: read # Needed for the GitHub Actions API
  pull-requests: read # Needed to check PR labels and numbers
  issues: read # Needed to check PR labels and numbers as they are technically issues in the GitHub API

jobs:
  enforce_version:
    name: Enforce Version
    runs-on:
      - ubuntu-latest # could also use ubuntu-slim
    steps:
      # This needs a branch protection rule configuring on the main branch that requires the PR to have one of the specified labels before it can be merged. This is to stop a PR being merged without a release label which would then not trigger the CD workflow to create a release and tag. The action will check the PR for the required labels and if not present it will fail the job and provide a message in the logs. It also outputs the PR number and labels as variables that can be used in other steps/jobs if needed. The action is flexible to be used in other repositories and allows configuration of the required labels and how they are validated (exactly one, any or all).
      # This may be either a pull_request OR push event. It should stop a merge to main unless a required release label is present. On an actual merge to main both events will fire but the push event will not have access to the PR information directly.
      - id: verify_version_label
        name: Verify version label
        uses: ./.github/actions/labels/enforce@main
        with:
          github_token: ${{ github.token }}
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          pr_number: ${{ github.event.pull_request.number }}
          pr_labels: ${{ join(github.event.pull_request.labels.*.name, ',') || '' }}
          required_labels: "internal,patch,minor,major"

  build_configuration:
    name: Build Configuration
    needs:
      - enforce_version
    runs-on:
      - ubuntu-latest # could also use ubuntu-slim
    # if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))
    # requires enforce_version to have passed: success()
    if: (!failure() && !cancelled())
    steps:
      - name: Print message 1
        run: echo "Hello, World PR!"

      - name: Print message 2
        if: (github.event.action == 'closed' && github.event.pull_request.merged == true)
        run: echo "PR merged event"
    
